### ISSUE TITLE
Add Support for enabling Lambda(Custom) Authorizers for HTTP endpoint in step function

### ISSUE THREAD

**Issue by quuuuu** [horike37/serverless-step-functions#115] opened 2018-04-18 18:21 UTC
# This is a Feature Proposal

## Description
* I use API Gateway to trigger my step function and I want to control the access to that gateway. I am using A lambda authorizer in my case.
* After looking into [this page](https://serverless.com/framework/docs/providers/aws/events/apigateway/#http-endpoints-with-custom-authorizers) , I added an lambda authorizer under the http endpoints in a similar way. I tried to deployed my change to AWS, but the authorizer did not show up. So, I suppose the step function plugin does not support adding lambda authorizer to the endpoint yet.
* Adding support to this would be really helpful to secure our endpoints. 

Thx!

**Comment by horike37** [comment] 2018-04-24 13:07
This is a duplicate of #38 so closing once.
Feel free to reopen if you want to continue any discussions

**Closed by horike37** 2018-04-24 13:07 UTC
