### ISSUE TITLE
Plugin Doesnt support adding custom authorization function to it API-G Event  

### ISSUE THREAD

**Issue by syedautherabbas** [horike37/serverless-step-functions#110] opened 2018-03-12 11:54 UTC
# This is a Feature Proposal as it is how the parent project serverless supports adding custom auth

## Description
Add ability to define custom auth functions 

For bug reports:
* What went wrong?
Cannot add auth function in serverless.yml, have to do it manually from console. 
* What did you expect should have happened?
auth function to have added and activated.
* What was the config you used?
stateMachines:
    CaseCrt:
      name: CaseCrt
      events:
        - http:
           path: /mainpath/casecreate
           method: post
           authorizer: ${file(./authorizer.yml)}

For feature proposals:
 Add custom auth feature similar to serverless lambda events
getStuff:
    handler: com.xyz.handler.getFunctionHandler
    timeout: 300
    description: To get Stuff
    events:
    - http:
        path: /mainPath/getstuff
        method: get
        authorizer: ${file(./authorizer.yml)}
        cors:
          origin: '*'

No Additional config

 

## Additional Data
* ***Serverless Framework Core Version ***:1.26.0
* ***The Plugin Version ***:1.3.0
* ***Operating System***: Unix
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by horike37** [comment] 2018-04-24 13:07
This is a duplicate of #38 so closing once.
Feel free to reopen if you want to continue any discussions.

**Closed by horike37** 2018-04-24 13:07 UTC
